### ISSUE TITLE
Incorrect config dir on CENTOS 7

### ISSUE THREAD

**Issue by hatdropper1977** [geerlingguy/ansible-role-kibana#13]
Hey, thanks for writing this!  One issue:

In roles/kibana/tasks/main.yml

The destination for kibana.yml should be:
/etc/kibana/kibana.yml and not /opt/kibana/config/kibana.yml"

**Comment by michz** [comment]
Same for (current) Debian based systems (tested with ubuntu).
Does it make sense to default to /etc/kibana/kibana.yml and make it configurable?

**Comment by b-long** [comment]
I can confirm, the directory is `/etc/kibana/kibana.yml` - also on RHEL 7

**Comment by geerlingguy** [comment]
Fixed in version 3.0.0, which also defaults to Kibana 6.x for everything (this role hadn't been updated in some time!).
