### ISSUE TITLE
fails to run in ELK playbook because of dependency to NGINX, a required group is missing

### ISSUE THREAD

**Issue by headmin** [geerlingguy/ansible-role-kibana#2]
quick fix: groupadd nginx    ## re-run playbook again 
suggested fix: add missing group creation to playbook

output (ubuntu 14.04.1LTS on vsphere 5.5):
TASK: [geerlingguy.kibana | Create Kibana user account.] *********************\* 
failed: [10.0.x.xxx] => {"failed": true, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/nginx/conf.d/kibana.htpasswd", "size": 45, "state": "file", "uid": 0}
msg: chgrp failed: failed to look up group nginx

FATAL: all hosts have already failed -- aborting

**Comment by barraponto** [comment]
Yeah, same issue here.

**Comment by geerlingguy** [comment]
Closing this issue, as the role now supports Kibana 4 and no longer _requires_ nginx/special nginx config (that may be split into a new and separate role).
