### ISSUE TITLE
No logrotate set

### ISSUE THREAD

**Issue by Lyr** [geerlingguy/ansible-role-kibana#26]
No logrotate configuration are been pushed during installation step which caused some trouble in FS side if nothing is done on the kibana log directory

**Comment by geerlingguy** [comment]
Logrotate configuration should be done outside of this role, as not all servers have logrotate, or even log to logfiles. I typically use this role to configure my logrotate setup: https://github.com/nickhammond/ansible-logrotate

**Comment by Lyr** [comment]
Ok, thank for the response and the link, I'm agree with this point.
