### ISSUE TITLE
we cannot setup customise version as 6.2.4 or 6.3.2. We can only setup the lastest version. 

### ISSUE THREAD

**Issue by lochanm2** [geerlingguy/ansible-role-kibana#28]
We are restricted to use ansible role as shown below
  
 - role: geerlingguy.kibana
      kibana_version: "6.x"
      kibana_server_port: 5601
      kibana_server_host: "0.0.0.0"
      kibana_elasticsearch_url: "http://x.x.x.x:9200"

but this doesn't work

   - role: geerlingguy.kibana
      kibana_version: "6.2.4"
      kibana_server_port: 5601
      kibana_server_host: "0.0.0.0"
      kibana_elasticsearch_url: "http://x.x.x.x:9200"

**Comment by andr1an** [comment]
Do you use RedHat or other RPM-based distro?

**Comment by geerlingguy** [comment]
There are ways using apt to lock versions if you need to (Debian/Ubuntu), similarly you can specify package versions strictly with RedHat/yum/dnf; it can get complicated supporting it easily across different distributions, but see my `geerlingguy.kubernetes` role for an example.

Usually it's recommended to stay within the latest release for a specific series on a distro, but I do realize with the Elastic.co stack (Kibana, Logstash, Filebeat, etc.) they often do major changes in a minor version, which kind of blows up the world (grr).

**Comment by moarpheus** [comment]
Hi Jeff. Thanks for creating this playbook. Is there any chance we could introduce another variable into playbook, for example like kibana_major_version (e.g 7.x ) and create repo like that?

```
[kibana-{{ kibana_major_version }}]
name=Kibana repository for {{ kibana_major_version }} packages
baseurl=https://artifacts.elastic.co/packages/{{ kibana_major_version }}/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
```

When installing Kibana we can specify the full kibana_version ( e.g. 7.5.2 ) then:

```
- name: Install Kibana.
  package:
    name: "kibana-{{ kibana_version }}"
    state: present
```

It is reasonably minor change and would help us to have visible locked version.

**Comment by jc36** [comment]
I have the same problem with new version 7.7.0
In order not to change the version of the elasticsearch, I must install kibana version 7.6.2, but with this role I do not see this possible without manual intervention.

**Comment by MachLearnPort** [comment]
> I have the same problem with new version 7.7.0
> In order not to change the version of the elasticsearch, I must install kibana version 7.6.2, but with this role I do not see this possible without manual intervention.

Here is a fix that worked for me:
In the `main.yml` of the kibana role tasks directory, replace 
```
- name: Install Kibana.
  package:
    name: "{{ kibana_package }}"
    state: "{{ kibana_package_state }}"
```
with:
```
- name: Install Kibana.
  package:
    name: "kibana-{{ kibana_package_version }}"
    state: "{{ kibana_package_state }}"
```
and add `kibana_package_version = <kibana version>` to the defaults>main.yml of the kibana role

**Comment by DerTim1** [comment]
If your host is Debian/Ubuntu (apt) you can use

    kibana_package: kibana=7.8.0

as variable to install e.g. version 7.8.0. This will run `apt-get install kibana=7.8.0`. Use `apt-cache madison kibana` to get a list of available versions.

**Comment by lochanm2** [comment]
It may work for newer version but it is getting failed with older versions. See the below output.

```TASK [geerlingguy.kibana : Add Kibana repository.] ******************************************************************************************************************************************
ok: [op-citation-test-kibana-01]

TASK [geerlingguy.kibana : Install Kibana.] *************************************************************************************************************************************************
fatal: [op-citation-test-kibana-01]: FAILED! => {"cache_update_time": 1599566090, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'kibana=6.8.12'' failed: E: Version '6.8.12' for 'kibana' was not found\n", "rc": 100, "stderr": "E: Version '6.8.12' for 'kibana' was not found\n", "stderr_lines": ["E: Version '6.8.12' for 'kibana' was not found"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information..."]}
```

**Comment by lochanm2** [comment]
```   
 - role: geerlingguy.kibana
      kibana_package: kibana=6.8.12
      kibana_server_port:       5601
      kibana_server_host:       "0.0.0.0"
```

**Comment by DerTim1** [comment]
@lochanm2 What is the output of `apt-cache madison kibana` (run directly on host)?
You may missing `kibana_version: "6.x"` in ansible. This is needed to install the correct package list.

**Comment by lochanm2** [comment]
```
root@op-citation-test-kibana-01:~# apt-cache madison kibana
    kibana |      7.9.1 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.9.0 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.8.1 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.8.0 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.7.1 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.7.0 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.6.2 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.6.1 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.6.0 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.5.2 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.5.1 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.5.0 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.4.2 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.4.1 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.4.0 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.3.2 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.3.1 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.3.0 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.2.1 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.2.0 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.1.1 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.1.0 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.0.1 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
    kibana |      7.0.0 | https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
root@op-citation-test-kibana-01:~#
```

**Comment by lochanm2** [comment]
and below is the kibana playbook

```
    - role: geerlingguy.kibana
      kibana_package: kibana=6.8.12
      kibana_version: "6.x"
      kibana_server_port:       5601
      kibana_server_host:       "0.0.0.0"
      kibana_elasticsearch_url: xxxxxxxxxxxxxx
```

**Comment by DerTim1** [comment]
@lochanm2 Ok, so you need to set `kibana_version: "6.x"`, than the task
```
- name: Add Kibana repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ kibana_version }}/apt stable main'
    state: present
    update_cache: true
```
inside the role will add 6.x-package list to your host. Afterwards `apt-cache madison kibana` should list Kibana 6 versions.

Maybe there is some caching problem. Delete the 7.x-package list from your host manually and run `apt-get update`. Than reprovision with ansible and see if the 6.x-package list will be installed.

**Comment by lochanm2** [comment]
Thanks for all your help. I would like to do it later and let you know how it works. Thanks again.
