### ISSUE TITLE
elasticsearch.url is not valid for kibana version 7.x

### ISSUE THREAD

**Issue by nkakouros** [geerlingguy/ansible-role-kibana#35]
The `elasticsearch.url` option has been removed in kibana version 7.x. It has been replaced by `elasticsearch.hosts` that accepts a list of hosts. The template shipping with the role will make 7.x fail.

**Comment by xcitan** [comment]
Hi, can someone tell if this will be fixed in this role?

**Comment by nkakouros** [comment]
You can use `kibana_config_template` to use a custom template until it is fixed.

**Comment by xcitan** [comment]
> You can use `kibana_config_template` to use a custom template until it is fixed.

works like charm! Thanks

**Comment by vkuehn** [comment]
probably if you have a template but I just start wrking myself into it. where to find a sufficient template ?
open since more than a months probably it gets fixed ?

**Comment by nkakouros** [comment]
I have resorted to creating my own role, the rest of you who have this issue just use a custom template or another role.
