### ISSUE TITLE
Add kibana_extra_config so I can set xpack options such as xpack.encryptedSavedObjects.encryptionKey

### ISSUE THREAD

**Issue by sspreitzer** [geerlingguy/ansible-role-kibana#62]
Hi

Thank you for maintaining this Ansible role.
Would be happy if you could add a `kibana_extra_config` config option as in your elasticsearch role.

Cheers
Sascha

**Comment by sandipb** [comment]
I had to add SSL cert to the Kibana config. I made a copy of the template to my playbook and edited the template with the vars I needed. This template overriding is explained in this role: https://github.com/geerlingguy/ansible-role-gitlab
