### ISSUE TITLE
Changing version of kibana does not install the changed version

### ISSUE THREAD

**Issue by seperman** [geerlingguy/ansible-role-kibana#7]
Changing version of kibana does not install the changed version.

First I had it install the default Kibana: 4.6.1
Then I changed the version to 4.5
It downloads 4.5 but does not install it.

**Comment by seperman** [comment]
I also did a manual `apt-get remove kibana` and then did vagrant provision again. It still install 4.6

What I see in the logs:

```
TASK [kibana : Add Kibana repository.] *****************************************
ok: [something] => {"changed": false, "repo": "deb https://packages.elastic.co/kibana/4.5/debian stable main", "state": "present"}

TASK [kibana : Install Kibana.] ************************************************
...
Unpacking kibana (from .../kibana_4.6.1_amd64.deb) ...\r\nSetting up kibana (4.6.1) ...
```

**Comment by seperman** [comment]
I also removed the `kibana_4.6.1_amd64.deb` manually and ran vagrant provision again. It still installs the latest version instead of the specified version.

**Comment by eli-betito** [comment]
I suffer from the same problem, is there a solution ?

**Comment by eli-betito** [comment]
@seperman @geerlingguy Has anyone solved the problem ?
